import { testPost } from "./test-post";
import ChalkBrain from "./../assets/global/ChalkBrain.png";

export const posts = [
  testPost,
  {
    title: "Tester boy",
    createdDate: "8/2/2023",
    description:
      "This is testing the post. Lick a post, or a salt block. In fact, go bite a can of beans until it opens. Yeah, your heard me. Make sure the beans are green.",
    image: ChalkBrain,
    tags: ["test", "chip"],
  },
  {
    title: "Wondering",
    createdDate: "8/4/2023",
    description: "Wonder about the world.",
    image: ChalkBrain,
    tags: ["hello", "me"],
  },
  {
    title: "Shell of command",
    createdDate: "9/29/2023",
    description: "Never thought I would be a turtle.",
    image: ChalkBrain,
    tags: ["math", "me"],
  },
  {
    title: "Swim through the Reef",
    createdDate: "9/30/2023",
    description: "Gah! Went the fish.",
    image: ChalkBrain,
    tags: ["dude", "math"],
  },
  {
    title: "Grassy pains",
    createdDate: "11/12/2023",
    description: "The grass is greener where you spray paint it.",
    image: ChalkBrain,
    tags: ["test", "hello"],
  },
  {
    title: "Listen for once",
    createdDate: "12/12/2023",
    description: "Pod pod pod pod pod pod podcast.",
    image: ChalkBrain,
    tags: ["math", "hello"],
  },
  {
    title: "Adele",
    createdDate: "12/15/2023",
    description: "Hello from the other siiiiiiide.",
    image: ChalkBrain,
    tags: ["test", "me"],
  },
  {
    title: "Pastry",
    createdDate: "12/19/2023",
    description: "Give that man a muffin",
    image: ChalkBrain,
    tags: ["me", "chip"],
  },
  {
    title: "Kangaroo on the plains",
    createdDate: "12/21/2023",
    description: "Give that woman a wallaby.",
    image: ChalkBrain,
    tags: ["hello", "chips"],
  },
  {
    title: "Imagine all the numbers",
    createdDate: "2/2/2024",
    description: "Random order in a random words.",
    image: ChalkBrain,
    tags: ["memememe", "chippy"],
  },
  {
    title: "IDK",
    createdDate: "5/19/2024",
    description: "AHDHFHSDHFLSDKFJALSDKFJ.",
    image: ChalkBrain,
    tags: ["tester", "home"],
  },
  {
    title: "i aM a SoftWArE DeVelOPer",
    createdDate: "5/20/2024",
    description: "sTARTING tO gO cRAZY.",
    image: ChalkBrain,
    tags: ["math", "mathematics"],
  },
  {
    title: "1 and a 2 and a 1 2 3 4",
    createdDate: "12/23/2024",
    description: "Numbers are important. 123456789",
    image: ChalkBrain,
    tags: ["school", "me"],
  },
  {
    title: "Test talk lol",
    createdDate: "12/25/2024",
    description: "There are 2 things I think 4 u.",
    image: ChalkBrain,
    tags: ["test", "chip"],
  },
];
